/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 01 16:27:00 GMT 2024
 */

package ex07;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ex07.Formula;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Formula_ESTest extends Formula_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Formula formula0 = new Formula(" 't+c*+>A y&h");
      int int0 = formula0.getB();
      assertEquals(0, int0);
      assertEquals(0, formula0.getA());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Formula formula0 = new Formula("3 Y%wM 5");
      int int0 = formula0.getB();
      assertEquals("Y%wM", formula0.getOpe());
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Formula formula0 = new Formula("3 Y?L 5");
      int int0 = formula0.getA();
      assertEquals("Y?L", formula0.getOpe());
      assertEquals(3, int0);
      assertEquals(5, formula0.getB());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Formula formula0 = new Formula("-3 6?M? 5");
      int int0 = formula0.getA();
      assertEquals("6?M?", formula0.getOpe());
      assertEquals((-3), int0);
      assertEquals(5, formula0.getB());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Formula formula0 = null;
      try {
        formula0 = new Formula((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ex07.Formula", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Formula formula0 = new Formula(" w'-Wx7 _jk");
      formula0.getOpe();
      assertEquals(0, formula0.getB());
      assertEquals(0, formula0.getA());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Formula formula0 = new Formula("r#hyz-NsAE");
      assertEquals(0, formula0.getA());
      assertEquals(0, formula0.getB());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Formula formula0 = new Formula("3 =H7uV^ -4");
      int int0 = formula0.getB();
      assertEquals((-4), int0);
      assertEquals("=H7uV^", formula0.getOpe());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Formula formula0 = new Formula("-3 6?M? 5");
      String string0 = formula0.getOpe();
      assertEquals("6?M?", string0);
      assertEquals(5, formula0.getB());
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Formula formula0 = new Formula("3 (eA}r &");
      int int0 = formula0.getA();
      assertEquals(0, formula0.getB());
      assertEquals(0, int0);
  }
}
